// Implements the reversible sender-to-receiver keepsake test flow inside the protected mobile runtime.
import { useState, type ReactNode } from "react";
import { ArrowLeftIcon, ArrowRightIcon, CheckCircledIcon, CheckIcon, EnvelopeClosedIcon, ImageIcon, Pencil1Icon, SpeakerLoudIcon } from "@radix-ui/react-icons";
import { AnimatePresence, MotionConfig, motion } from "motion/react";
import { KeyboardInput, KeyboardTextarea, MobileScroll, useKeyboard } from "./mobile";

type Screen = "shelf" | "person" | "write" | "material" | "preview" | "share" | "complete" | "arrival" | "deferred" | "unavailable" | "reveal" | "kept" | "discarded";
type Material = "none" | "photo" | "voice";
type VoiceState = "ready" | "playing" | "finished";
const sender = "Ethan";

export default function Prototype() {
  const [screen, setScreen] = useState<Screen>("shelf");
  const [recipient, setRecipient] = useState("Maya");
  const [reason, setReason] = useState("the way you made moving feel less scary");
  const [body, setBody] = useState("I keep thinking about that day. You made a hard thing feel lighter without making a big deal of it. I noticed.");
  const [material, setMaterial] = useState<Material>("none");
  const [alternative, setAlternative] = useState("The two of us sitting among half-open moving boxes, laughing.");
  const [voice, setVoice] = useState<VoiceState>("ready");
  const [failed, setFailed] = useState(false);
  const [discarding, setDiscarding] = useState(false);
  const [keptDiscarding, setKeptDiscarding] = useState(false);
  const [kept, setKept] = useState(false);
  const keyboard = useKeyboard();
  const go = (next: Screen) => { keyboard.hide(); setScreen(next); };
  const validPerson = recipient.trim() !== "" && reason.trim() !== "";
  const validWrite = body.trim() !== "";
  const validMaterial = material === "none" || alternative.trim() !== "";
  const back = screen === "person" ? "shelf" : screen === "write" ? "person" : screen === "material" ? "write" : screen === "preview" ? "material" : "preview";
  const startNew = () => {
    setRecipient("");
    setReason("");
    setBody("");
    setMaterial("none");
    setAlternative("");
    setVoice("ready");
    setFailed(false);
    setDiscarding(false);
    setKeptDiscarding(false);
    go("person");
  };

  return <MotionConfig reducedMotion="user"><MobileScroll className="app-screen keepsake-app"><main className="keepsake-shell" aria-label="Exploratory friendship keepsake prototype">
    {screen !== "reveal" && screen !== "complete" && <header className="prototype-topbar">{!["shelf", "arrival", "deferred", "unavailable", "kept", "discarded"].includes(screen) ? <button className="ink-button icon-button" aria-label="Go back" onClick={() => go(back)}><ArrowLeftIcon /></button> : <span className="topbar-spacer" />}<button className="role-switch" onClick={() => go(["arrival", "deferred", "unavailable", "reveal", "kept", "discarded"].includes(screen) ? "shelf" : "arrival")}>{["arrival", "deferred", "unavailable", "reveal", "kept", "discarded"].includes(screen) ? "sender view" : "receiver view"}</button></header>}
    <AnimatePresence mode="wait">
      {screen === "shelf" && <Shelf key="shelf" recipient={recipient} kept={kept} onStart={() => go("person")} onArrival={() => go("arrival")} onKept={() => go("kept")} />}
      {screen === "person" && <Person key="person" recipient={recipient} reason={reason} setRecipient={setRecipient} setReason={setReason} enabled={validPerson} onNext={() => go("write")} />}
      {screen === "write" && <Write key="write" body={body} setBody={setBody} enabled={validWrite} onNext={() => go("material")} />}
      {screen === "material" && <MaterialStep key="material" material={material} alternative={alternative} setMaterial={setMaterial} setAlternative={setAlternative} enabled={validMaterial} onNext={() => go("preview")} />}
      {screen === "preview" && <Preview key="preview" recipient={recipient} body={body} material={material} alternative={alternative} onEdit={() => go("write")} onShare={() => { setFailed(false); go("share"); }} />}
      {screen === "share" && <Share key="share" failed={failed} onSend={() => go("complete")} onFail={() => setFailed(true)} onPreview={() => go("preview")} />}
      {screen === "complete" && <Complete key="complete" recipient={recipient} onNew={startNew} onReceiver={() => go("arrival")} onLeave={() => go("shelf")} />}
      {screen === "arrival" && <Arrival key="arrival" recipient={recipient} onOpen={() => go("reveal")} onDefer={() => go("deferred")} onUnavailable={() => go("unavailable")} />}
      {screen === "deferred" && <Deferred key="deferred" onReturn={() => go("arrival")} onLeave={() => go("shelf")} />}
      {screen === "unavailable" && <Unavailable key="unavailable" onReturn={() => go("arrival")} onLeave={() => go("shelf")} />}
      {screen === "reveal" && <Reveal key="reveal" recipient={recipient} body={body} material={material} alternative={alternative} voice={voice} onVoice={() => setVoice((v) => v === "ready" ? "playing" : v === "playing" ? "finished" : "playing")} discarding={discarding} onKeep={() => { setKept(true); go("kept"); }} onClose={() => go("arrival")} onDiscard={() => setDiscarding(true)} onConfirm={() => { setDiscarding(false); setKept(false); go("discarded"); }} onCancel={() => setDiscarding(false)} />}
      {screen === "kept" && <Kept key="kept" recipient={recipient} discarding={keptDiscarding} onClose={() => go("shelf")} onDiscard={() => setKeptDiscarding(true)} onConfirm={() => { setKeptDiscarding(false); setKept(false); go("discarded"); }} onCancel={() => setKeptDiscarding(false)} />}
      {screen === "discarded" && <Discarded key="discarded" onRestore={() => go("arrival")} onLeave={() => go("shelf")} />}
    </AnimatePresence>
  </main></MobileScroll></MotionConfig>;
}

function Page({ children, className = "" }: { children: ReactNode; className?: string }) { return <motion.section className={`keepsake-page ${className}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} transition={{ duration: 0.22 }}>{children}</motion.section>; }
function Shelf({ recipient, kept, onStart, onArrival, onKept }: { recipient: string; kept: boolean; onStart: () => void; onArrival: () => void; onKept: () => void }) { return <Page className="shelf-page"><p className="prototype-label">exploratory prototype · local sample state</p><div className="shelf-intro"><h1>one thing, for one person</h1><p>A finite object for a thought you already had. It is not a conversation prompt.</p></div>{kept && <button className="kept-object" onClick={onKept}><span>for {recipient}</span><small>kept locally by the receiver</small></button>}<div className="shelf-actions"><button className="ink-button primary-ink" onClick={onStart}><Pencil1Icon /> make something</button><button className="ink-button quiet-ink" onClick={onArrival}>view sample arrival <ArrowRightIcon /></button></div><p className="quiet-note">No feed, streak, reminder, or suggested person.</p></Page>; }
function Person({ recipient, reason, setRecipient, setReason, enabled, onNext }: { recipient: string; reason: string; setRecipient: (value: string) => void; setReason: (value: string) => void; enabled: boolean; onNext: () => void }) { return <Page><h2>start with someone you know</h2><label className="writing-label" htmlFor="recipient">their name</label><KeyboardInput id="recipient" className="hand-input name-input" value={recipient} onChange={(e) => setRecipient(e.target.value)} autoComplete="off" /><p className="field-note">Local prototype entry only. No contacts are accessed.</p><label className="writing-label" htmlFor="reason">what made you think of them?</label><KeyboardTextarea id="reason" className="hand-input reason-input" value={reason} onChange={(e) => setReason(e.target.value)} /><p className="field-note">Use one real reason or moment. The prototype cannot write it for you.</p><button className="ink-button primary-ink page-next" disabled={!enabled} onClick={onNext}>write the note <ArrowRightIcon /></button></Page>; }
function Write({ body, setBody, enabled, onNext }: { body: string; setBody: (value: string) => void; enabled: boolean; onNext: () => void }) { return <Page><h2>write it like only you could</h2><label className="writing-label" htmlFor="body">your words</label><KeyboardTextarea id="body" className="hand-input letter-input" value={body} onChange={(e) => setBody(e.target.value)} /><p className="field-note">This note is the object. It must be written before you continue.</p><button className="ink-button primary-ink page-next" disabled={!enabled} onClick={onNext}>add one thing, or skip <ArrowRightIcon /></button></Page>; }
function MaterialStep({ material, alternative, setMaterial, setAlternative, enabled, onNext }: { material: Material; alternative: string; setMaterial: (value: Material) => void; setAlternative: (value: string) => void; enabled: boolean; onNext: () => void }) { return <Page><h2>one thing that carries the memory</h2><p className="page-intro">Optional. A text-only object is complete.</p><div className="material-list" role="group" aria-label="Choose zero or one supporting material"><button className={`material-choice ${material === "none" ? "selected" : ""}`} aria-pressed={material === "none"} onClick={() => setMaterial("none")}>no supporting material {material === "none" && <CheckIcon className="choice-check" />}</button><button className={`material-choice ${material === "photo" ? "selected" : ""}`} aria-pressed={material === "photo"} onClick={() => setMaterial("photo")}><ImageIcon /> sample photo <span>simulated</span>{material === "photo" && <CheckIcon className="choice-check" />}</button><button className={`material-choice ${material === "voice" ? "selected" : ""}`} aria-pressed={material === "voice"} onClick={() => setMaterial("voice")}><SpeakerLoudIcon /> sample voice note <span>simulated</span>{material === "voice" && <CheckIcon className="choice-check" />}</button></div>{material !== "none" && <><label className="writing-label" htmlFor="alternative">{material === "photo" ? "photo description" : "voice transcript"}</label><KeyboardTextarea id="alternative" className="hand-input alternative-input" value={alternative} onChange={(e) => setAlternative(e.target.value)} /><p className="field-note">This text is the accessible equivalent for the simulated material.</p></>}<button className="ink-button primary-ink page-next" disabled={!enabled} onClick={onNext}>preview the object <ArrowRightIcon /></button></Page>; }
function Preview({ recipient, body, material, alternative, onEdit, onShare }: { recipient: string; body: string; material: Material; alternative: string; onEdit: () => void; onShare: () => void }) { return <Page className="preview-page"><p className="prototype-label">private object preview · not delivered</p><div className="preview-object"><span>for {recipient}</span><p>{body}</p>{material !== "none" && <div className="preview-material"><span>{material === "photo" ? "sample photo" : "sample voice note"} · simulated</span><small>{alternative}</small></div>}<footer>from {sender}</footer></div><p className="field-note">This is a finite object, not a chat message.</p><button className="ink-button primary-ink" onClick={onShare}>make a simulated share link <ArrowRightIcon /></button><button className="ink-button quiet-ink" onClick={onEdit}>edit the object</button></Page>; }
function Share({ failed, onSend, onFail, onPreview }: { failed: boolean; onSend: () => void; onFail: () => void; onPreview: () => void }) { return <Page className="share-page"><h2>{failed ? "the link was not made" : "ready to pass privately"}</h2><p>{failed ? "Nothing was sent. Your note and preview are still here in this local prototype." : "This prototype simulates a private share link. It does not deliver, store, or identify anyone outside this screen."}</p><button className="ink-button primary-ink" onClick={onSend}>{failed ? "try simulated share again" : "simulate sharing the link"} <ArrowRightIcon /></button><button className="ink-button quiet-ink" onClick={failed ? onPreview : onFail}>{failed ? "back to preview" : "simulate link failure"}</button></Page>; }
function Complete({ recipient, onNew, onReceiver, onLeave }: { recipient: string; onNew: () => void; onReceiver: () => void; onLeave: () => void }) { return <Page className="sender-complete"><CheckCircledIcon className="completion-icon" aria-hidden="true" /><h2>the giving part is complete</h2><p>A simulated private link has been made for {recipient}. There is no open, keep, read, reply, or follow-up tracking for you to check.</p><button className="ink-button primary-ink" onClick={onNew}>make another object</button><button className="ink-button quiet-ink" onClick={onReceiver}>view receiver arrival</button><button className="text-button" onClick={onLeave}>leave prototype</button></Page>; }
function Arrival({ recipient, onOpen, onDefer, onUnavailable }: { recipient: string; onOpen: () => void; onDefer: () => void; onUnavailable: () => void }) { return <Page className="arrival-page"><p className="prototype-label">receiver view · simulated arrival</p><div className="arrival-space"><button className="sealed-object" onClick={onOpen} aria-label={`Open private keepsake from ${sender} for ${recipient}`}><EnvelopeClosedIcon className="sealed-icon" aria-hidden="true" /><small>private keepsake</small></button></div><h2>{sender} made something private for you.</h2><p>You can open it now, or leave it for another time.</p><button className="ink-button primary-ink" onClick={onOpen}>open when ready <ArrowRightIcon /></button><button className="ink-button quiet-ink light-ink" onClick={onDefer}>open another time</button><button className="text-button arrival-test-link" onClick={onUnavailable}>simulate unavailable link</button></Page>; }
function Deferred({ onReturn, onLeave }: { onReturn: () => void; onLeave: () => void }) { return <Page className="deferred-page"><h2>left unopened</h2><p>No signal was sent to Ethan. This private local demo will not remind you.</p><button className="ink-button quiet-ink" onClick={onReturn}>return to arrival</button><button className="text-button" onClick={onLeave}>leave local demo</button></Page>; }
function Unavailable({ onReturn, onLeave }: { onReturn: () => void; onLeave: () => void }) { return <Page className="unavailable-page"><p className="prototype-label">simulated invalid or expired link</p><h2>this keepsake cannot be opened</h2><p>No private content has been shown. A real service would explain whether the link expired, was revoked, or reached the wrong person without exposing the message.</p><button className="ink-button quiet-ink" onClick={onReturn}>return to sample arrival</button><button className="text-button" onClick={onLeave}>leave local demo</button></Page>; }
function Reveal({ recipient, body, material, alternative, voice, onVoice, discarding, onKeep, onClose, onDiscard, onConfirm, onCancel }: { recipient: string; body: string; material: Material; alternative: string; voice: VoiceState; onVoice: () => void; discarding: boolean; onKeep: () => void; onClose: () => void; onDiscard: () => void; onConfirm: () => void; onCancel: () => void }) { return <motion.section className="keepsake-page full-object" initial={{ opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .24 }}><span className="letter-recipient">for {recipient} · from {sender}</span><p className="revealed-letter">{body}</p>{material === "photo" && <div className="revealed-material"><ImageIcon /><div><strong>sample photo · simulated</strong><span>{alternative}</span></div></div>}{material === "voice" && <div className="revealed-material"><button className="voice-control" onClick={onVoice} aria-label={voice === "ready" ? "Play simulated voice note" : voice === "playing" ? "Finish simulated voice note" : "Replay simulated voice note"}><SpeakerLoudIcon /> {voice === "ready" ? "play voice" : voice === "playing" ? "playing… tap to finish" : "play again"}</button><span className="material-transcript"><strong>Transcript</strong>{alternative}</span></div>}{discarding ? <div className="discard-confirm" role="alert"><p>Discard this local prototype copy? It can be restored during this session. The sender will not be told.</p><button className="ink-button quiet-ink" onClick={onConfirm}>discard local copy</button><button className="text-button" onClick={onCancel}>cancel</button></div> : <div className="reveal-actions"><button className="ink-button quiet-ink" onClick={onKeep}>keep locally</button><button className="ink-button quiet-ink" onClick={onClose}>close for now</button><button className="ink-button quiet-ink" onClick={onDiscard}>discard</button></div>}</motion.section>; }
function Kept({ recipient, discarding, onClose, onDiscard, onConfirm, onCancel }: { recipient: string; discarding: boolean; onClose: () => void; onDiscard: () => void; onConfirm: () => void; onCancel: () => void }) { return <Page className="kept-page"><div className="kept-paper"><span>for {recipient}</span><p>Kept only in this prototype session.</p></div><h2>kept is one possible ending</h2><p>It is not a signal to the sender. You can close it, or remove this local copy.</p><button className="ink-button quiet-ink" onClick={onClose}>close the keepsake</button>{discarding ? <div className="discard-confirm"><p>Discard this local prototype copy? The sender will not be told.</p><button className="ink-button quiet-ink" onClick={onConfirm}>discard local copy</button><button className="text-button" onClick={onCancel}>cancel</button></div> : <button className="text-button" onClick={onDiscard}>discard local copy</button>}</Page>; }
function Discarded({ onRestore, onLeave }: { onRestore: () => void; onLeave: () => void }) { return <Page className="discarded-page"><h2>local copy removed</h2><p>The sender is not told. For this prototype session, you can restore the simulated object or leave.</p><button className="ink-button quiet-ink" onClick={onRestore}>restore simulated object</button><button className="text-button" onClick={onLeave}>leave prototype</button></Page>; }
