#!/usr/bin/env python3
"""Build a deterministic, source-labelled context bundle for deck agents."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "deck" / "generated" / "context.md"
SOURCES = (
    "WIKI/BRIEF.md",
    "WIKI/JUDGING.md",
    "WIKI/DECISIONS.md",
    "WIKI/IDEAS.md",
    "WIKI/EVIDENCE.md",
    "WIKI/TESTS.md",
    "WIKI/TACTICAL_PLAN.md",
)


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build_bundle() -> str:
    parts = [
        "<!-- This generated bundle gives deck agents one source-labelled view of the authoritative project context. -->",
        "# Generated deck context",
        "",
        "Generated from repository Markdown. Do not edit this file directly.",
        "",
    ]
    for relative in SOURCES:
        source = ROOT / relative
        if not source.is_file():
            raise FileNotFoundError(f"Required deck source is missing: {relative}")
        content = source.read_text(encoding="utf-8").strip()
        parts.extend(
            (
                f"## Source: `{relative}`",
                "",
                f"SHA-256: `{digest(content)}`",
                "",
                content,
                "",
            )
        )
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT.relative_to(ROOT)})",
    )
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_bundle(), encoding="utf-8")
    print(output.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
